Space Exploration Project - Rockets, Missions and Profile pages
Ellon-M/space-exploration pull request #28
Opened 2023-02-03 20:18 UTC by Ellon-M

## Changes

 - Set up the project with `create-react-app` and linters for JavaScript and CSS.
 - Set up `redux toolkit` and configured the redux store.
 - Wrote action creators and actions for the rockets.
 - Fetched rocket data from the SpaceX API.
 -  Wrote action creators and actions for the missions.
 - Fetched mission data from the SpaceX API.
 - Rendered the rockets and the missions on the UI's of their respective pages.
 - Wrote conditional switch statements for the buttons to change the functionality when the state is altered.
 - Displayed the reserved rockets and joined missions on the `Profile.js` page.
 - Wrote unit tests for the rockets, missions, and navigation bar components.

2023-02-03 21:01 UTC, danmainah requested changes
Hi @Ellon-M and @quavo19 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Gitflow was correctly used
✔️  Good design


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-03 21:01 UTC, danmainah commented on src/components/Profile.js
> +            </tbody>
- [ ] Kindly ensure the reserved rockets are displayed using the filter method as you did in the missions, this is a project requirement 
![image](https://user-images.githubusercontent.com/61408860/216709727-dcebcf19-3e90-43ac-8aed-59e41505addd.png)

2023-02-03 22:02 UTC, quavo19 commented on src/components/Rocket.js
> +        </p>
@danmainah please do you mean the reserved badge?

2023-02-04 09:33 UTC, emmiiorji requested changes
Hi @Ellon-M and @quavo19, 

# Status: Changes Required ♻️

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ![A little bit more](https://user-images.githubusercontent.com/20554583/216759221-ccfb4fd9-2597-4933-a26a-ca42a63cc7eb.gif)

## Good Highlights✔️

- Good commit messages
- Adhered to GitHub flow
- Requested changes have been implemented


 ## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-04 09:33 UTC, emmiiorji commented on .eslintrc.json
> +  }
Could you make sure you use the unmodified given linters configuration for react/redux projects? The [.eslintrc.json](https://github.com/microverseinc/linters-config/blob/master/react-redux/.eslintrc.json) and [linters.yml](https://github.com/microverseinc/linters-config/blob/master/react-redux/.github/workflows/linters.yml) files is supposed to match yours.

Linters represent coding standards you share with your team and prevent divergent coding styles. Most of the time, they also enforce the best coding practices.

Your .eslintrc.json vs correct config:
![image](https://user-images.githubusercontent.com/20554583/216759356-ef6b8e0b-ed6a-4187-bbbc-f5118dcaf58b.png)

Your linters.yml vs correct config:
![image](https://user-images.githubusercontent.com/20554583/216759960-251e991d-e476-44ea-b57f-0c6333359971.png)

2023-02-04 10:26 UTC, levy002 approved these changes
## Hello @Ellon-M  & @quavo19 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## Status: APPROVED :fire:  :fire: 

## Highlights
- Professional README file :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-04 10:27 UTC, quavo19 commented
@levy002 thank you sir

2023-02-04 12:24 UTC, merged